Criacao de RPG_Character: domain/controller/persitence
enricolo4/rpg_character pull request #1
Opened 2020-05-06 02:45 UTC by raphaelDuff

Please review and approve

2020-05-06 23:58 UTC, enricolo4 requested changes

2020-05-06 23:58 UTC, enricolo4 commented on main/main.py
> +    serve(app=application, host="127.0.0.1", port=5555)
Remover essa parte

2020-05-07 00:09 UTC, raphaelDuff commented
Removed the server and port from the main

2020-05-07 00:10 UTC, raphaelDuff commented on main/main.py
> +    serve(app=application, host="127.0.0.1", port=5555)
OK. Isso foi substituído pelo hupper -m waitress --port=8000 main.main:application

2020-05-07 00:26 UTC, enricolo4 approved these changes

2020-05-07 00:27 UTC, merged